site_name: howird

theme:
  name: null
  custom_dir: 'simpleblog/'
  features:
    - content.code.annotate

nav:
  - About Me: 'index.md'

  - Project Logs:
    - path: 'project-logs/index.md'
    - sections:
      - keebwird: 'project-logs/keebwird'
      - watonomous: 'project-logs/watonomous'
      - watolink: 'project-logs/watolink'
      - misc: 'project-logs/misc'

  - Learning Wiki:
    - path: 'learning-wiki/index.md'
    - sections:
      - computational neuroscience: 'learning-wiki/computational-neuroscience'
      - deep learning: 'learning-wiki/deep-learning'
      - quick notes: 'learning-wiki/quick-tips'
      - open3d: 'learning-wiki/open3d'

  - Resources:
    - path: 'resources/index.md'
    - sections:
      - courses: 'resources/courses' 
      - playlists: 'resources/playlists'
      # - misc: 'resources/misc'
  
  - Photos: 'photos.md'

markdown_extensions:
# mathjax, see squidfunk.github.io/mkdocs-material/reference/mathjax/
  - pymdownx.arithmatex:
      generic: true

# codeb locks, squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - attr_list

extra_javascript:
# mathjax squidfunk.github.io/mkdocs-material/reference/mathjax/
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-video