site_name: Howard Nguyen-Huu

theme:
  name: null
  custom_dir: 'simpleblog/'

nav:
  - Start Here: 'index.md'
  - Project Logs: 'project-logs/index.md'
  - My Learning Wiki: 'learning-wiki/index.md'
  # - Personal Thoughts: 'personal.md'
  - Favorites: 'favorites.md'
  - About Me: 'about.md'
  - Photos: 'photos.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list

extra_javascript:
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search