site_name: Howard Nguyen-Huu

theme:
  name: null
  custom_dir: 'simpleblog/'

nav:
  - Start Here: 'index.md'
  - Project Logs: 'project-logs/index.md'
  - Learning Logs: 'learning-logs/index.md'
  - Personal Thoughts: 'personal.md'
  - Favourites: 'favourites.md'
  - About Me: 'about.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

site_favicon: 'img/favicon.ico'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js